language: php

php:
  - '7.1.3'
  - '7.2'
  - '7.3'

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update
  - travis_retry composer install

script: vendor/bin/phpunit -c ./phpunit.xml.dist
